#!/usr/bin/perl

use strict;
use warnings;
use File::Glob ':glob';
use Cwd;

# Get current working directory
my $pwd = getcwd();

# Append pwd to the filter string
my $filter = "$pwd/screenshot.png";

if (-e $filter) {
    chomp($filter);
    # Open the last created file with an absolute path
    my $command = "gimp-2.10\ ./screenshot.png";
    system($command) == 0
        or die "Failed to execute GIMP: $!";
} else {
    print "Screenshot failed or was canceled.\n";
}

my $command2 = 'rm ./screenshot.png';
my $erasing = 'echo "screenshot.png has been ereased."';
system("$command2");
system("$erasing");
