#!/usr/bin/perl

use strict;
use warnings;
use File::Glob ':glob';
use Cwd;

# Get current working directory
my $pwd = getcwd();

# Append pwd to the filter string
my $filter = "$pwd/screenshot.png";

if (-e $filter) {
    chomp($filter);
    print "Opening Gimp\n";
    # Open the last created file with an absolute path
    my $command = "gimp-2.10\ --new-instance\ ./screenshot.png";
    if(system($command) != 0) { 
        die "Failed to execute GIMP: $!";
    }
} else {
    print "Failed to open screenshot.png with Gimp.";
}

my $command2 = 'rm ./screenshot.png';
system("$command2");
