#!/usr/bin/perl
use strict;
use warnings;

# Get the current working directory
my $current_dir = `pwd`;
chomp($current_dir);

# Define the full path for the screenshot file
my $file_path = "$current_dir/screenshot.png";

# Use gnome-screenshot to take the screenshot and save it
my $command = "gnome-screenshot --area -f \"$file_path\"";
system($command);

if (-e $file_path) {
    print "Screenshot saved successfully!\n";
} else {
    print "Screenshot failed or was canceled.\n";
}
