#!/usr/bin/perl
use strict;
use warnings;

# Define the commands
my $command1 = "/usr/local/bin/screenshot";
my $command2 = "/usr/local/bin/editfile";

# Execute the first command
system($command1);

# Execute the second command only if the first was successful
my $exit_code2 = system($command2);
if ($exit_code2 == 0) {
        print "Successfully opened file in GIMP.\n";
}else {
	die "Failed to execute GIMP (exit code $exit_code2): $!";
}
