#!/usr/bin/perl
use strict;
use warnings;

# Define the commands
my $command1 = `pwd`;
chomp($command1);
my $command2 = $command1;
$command1 .= '/screenshot';
$command2 .= '/editfile';

#Retrieve errors
my $status1 = system($command1);
my $status2;
if ($status1 == 0) {
    $status2 = system($command2);
    if ($status2 != 0) {
        print "Gimp was not executed successfully!\n";
    }
}
